base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 3303
  username: root
  password: kenrome001

development:
  <<: *base
  database: metro_style

test:
  <<: *base
  database: metro_style

production:
  <<: *base
  database: metro_style
